config/routes.rb
Dotastic::Application.routes.draw do
  root 'home#index'

  resources :todos do
    collection do
      post 'done'
    end
  end
  match 'auth/:providers/callback', to: 'sessions#create', via: :get
  match 'auth/failure', to: redirect("/"), via: :get
  match 'signout', to: 'sessions#destroy', via: :get, as: 'signout'

  

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :todo, presence: true
  validates :todo, length: { minimum: 1 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos
  def self.from_omniauth(auth)
    where(auth.slice("provider","uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.nickname = auth["info"]["nickname"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.image = auth["info"]["image"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to todos_path, notice: "Signed in"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :destroy, :update]
  def index
    @todos = Todo.where(user_id: session[:user_id]).order("created_at ASC")
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = session[:user_id]
    respond_to do |format|
      format.html do
        if @todo.save
          flash[:notice] = "Todo has been created."
          redirect_to @todo
        else
          flash[:alert] = "Todo has not been created."
          render :new
        end
      end
      format.js do
        unless @todo.save
          render text: @todo.errors.full_messages.join, status: :unprocessable_entity
        end
      end
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    respond_to do |format|
      format.html do
        if @todo.update(todo_params)
          flash[:notice] = "Todo has been updated."
          redirect_to @todo
        else
          flash[:alert] = "Todo has not been updated."
          render action: "edit"
        end
      end
      format.js do
        unless @todo.update(todo_params)
          render text: @todo.errors.full_messages.join, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    flash[:notice] = "Todo has been deleted."
    redirect_to todos_path
  end

  def done
    @todo = Todo.find(params[:id])
    if @todo.done
      @todo.update_attribute(:done, false)
    else
      @todo.update_attribute(:done, true)
    end
  end

  private
  def todo_params
    params.require(:todo).permit(:todo)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The todo you are looking for could not be found."
    redirect_to todos_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<h2>Todotastic What?</h2>

Todotastic is a project that I completed for my advanced rails course. The
base Rails project is pretty basic, however I was tasked with utilizing 
different technologies for Rails. 

It's a basic Todo application. Perhaps someday I will improve it's 
functionality. 

Please log in with your Github account. 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
        <h1><%= link_to "Todotastic!", "/" %></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <% if current_user %>
            <li class="divider"></li>
            <li><%= link_to "#{current_user.nickname}, Sign out", signout_path %></li>
          <% else %>
            <li >
               <%= link_to "Sign in via Github", "/auth/github" %>
            </li>
            <% end %>
        </ul>
      </section>
    </nav>
    <div class="row">
      <% flash.each do |key, value| %>
        <div data-alert class='alert-box' id='<%= key %>'>
          <%= value %>
          <a href="" class='close'>&times;</a>
        </div>
      <% end %>

      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
    <script>
      $(function(){
        $(".todo_status").change(function() {
          $.ajax({
            url: "/todos/done",
            data: "id="+$(this).val(),
            type: "POST"
          });
        });
      });
</script>
  </body>
</html>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@todo.errors.count, "error") %>
    prohibited this todo from being saved:</h2>
    <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@todo, remote: true) do |f| %>
    <%= f.text_field :todo %>
    <%= f.submit %>
<% end %>

app/views/todos/_todo.html.erb
<li>
   <%= check_box_tag 'todo_status', todo.id, todo.done, class: 'todo_status' %>
   <%= link_to todo.todo, todo %>
</li>

app/views/todos/create.js.erb
$('#new_todo').remove();
$('#new_link').show();
$('.todo_list').append('<%= j render(@todo) %>');

app/views/todos/done.js.erb
if ($('li#todo_<%= @todo.id %> > input').prop('checked'))
{
  $('li#todo_<%= @todo.id %>').appendTo($('ul#completed_todos'));
}
else
{
  $('li#todo_<%= @todo.id %>').appendTo($('ul#incomplete_todos'));
}

app/views/todos/edit.html.erb
<h2> Edit Todo </h2>
<%= render "form" %>

app/views/todos/edit.js.erb
$('#todo_<%= @todo.id %>').hide().after('<%= j render("form") %>')

app/views/todos/index.html.erb
<%= link_to "New Todo", new_todo_path, remote: true, id: :new_link %>
<h3>Todos:</h2>
<ul class="incomplete_todos" id="incomplete_todos">
  <% @todos.each do |todo| %>
    <% if todo.done != true %>
    <li id="todo_<%= todo.id %>">
    <%= check_box_tag 'todo_status', todo.id, todo.done, class: 'todo_status' %>
    <%= link_to todo.todo, edit_todo_path(todo), remote: true %></li>
  <% end %>
<% end %>
</ul>
<h3>Completed: </h2>
<ul class="completed_todos" id="completed_todos">
  <% @todos.each do |todo| %>
    <% if todo.done == true  %>
      <li id="todo_<%= todo.id %>">
      <%= check_box_tag 'todo_status', todo.id, todo.done, class: 'todo_status' %>
      <%= link_to todo.todo, edit_todo_path(todo), remote: true %></li>
    <% end %>
  <% end %>
</ul>

app/views/todos/new.html.erb
<h2>New Todo</h2>
<%= render "form" %>

app/views/todos/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>')

app/views/todos/show.html.erb
<h2><%= @todo.id %></h2>
<p>
  <%= @todo.todo %>
</p>
<p>
  <%= link_to "Delete Todo", todo_path(@todo), method: :delete, data: { confirm: "Are you sure you want to delete this todo?"} %>
</p>
<p>
  <%= link_to "Edit Todo", edit_todo_path(@todo) %>
</p>

app/views/todos/update.js.erb
$('#edit_todo_<%= @todo.id %>').remove();
$('#todo_<%= @todo.id %>').replaceWith('<%= j render(@todo) %>');